### ISSUE TITLE
The List crashes and shows me a blank screen now.

### ISSUE THREAD

**Issue by turion** [creativecommons/list#181]
I installed the latest version a few minutes ago. I could login and see photo requests and save them to my list. When I took my first photo, the List crashed without further ado. When I open it again, it just shows a white screen. A shame, I liked the app.

**Comment by mattl** [comment]
Hey @turion -- can you tell me a little bit more about your phone/tablet? Which version of Android are you running? Do you have Google apps installed?

**Comment by perpetuatingcuriosity** [comment]
The blank screen seems to be a problem with Google Analytics. Working on it! What version of Play Services do you have?

**Comment by perpetuatingcuriosity** [comment]
This should be fixed with the latest commit.

**Comment by turion** [comment]
I'll gladly test it, but is there a new binary to download it?

**Comment by mattl** [comment]
Yes, hopefully you got another email from us. If not,
https://thelist.creativecommons.org/beta/

**Comment by turion** [comment]
Sorry, didn't have time earlier. I didn't get another email. I downloaded the package from the link you mentioned. I still see the white screen. Is the binary updated at all? Do I have to delete some settings files from somewhere before I try again?

**Comment by turion** [comment]
I deleted the data of the app via the android application manager. It still crashes when I submit photos, but I can start the app afterwards.

**Comment by mattl** [comment]
We have a new version coming out in a few days time that fixes this.
